### ISSUE TITLE
<C-j>/<NL> remapping to <C-n> is not usable for C-Language.

### ISSUE THREAD

**Issue by somedadaism** [Netherdrake/Dotfiles#3]
Kudos for sharing these great Dotfiles.
I opened this issue because the way I installed this config there has appeared an issue with the mapping for autocomplete support <C-j> being unavailable and causing (at least that is my feeling) counter intuitive behavior for C language-type files. The reason for that is the mapping of that key in the c.vim bundle to:
<C-R>=C_JumpCtrlJ()<CR>
I don't know if this behavior is accepted, I made a mistake at my installation or you would prefer to have the mapping uniformly over all kinds of program. It bugged me and took a little while to figure out, so I wanted to share with other users. Sorry if you fell this issue was unnecessary, I just wanted to give my feedback.

**Comment by Netherdrake** [comment]
Hey, I'm super happy to see people use these configs.

Unfortunately I don't write any C (I only use the plugin for syntax highlighting to read C), so I was not aware of the issue.

There are many language plugins with their own mappings, and unfortunately conflicts arise from time to time. 

I suggest you create a fork, and disable this particular remapping, or overload mapping in `c.vim`. I will accept the latter as a PR.

**Comment by somedadaism** [comment]
I will gladly do so, erasing some lines in c.vim fixes that, but I would like to ask a question with respect to this: If I solely erase these lines, wouldn't a PluginUpdate recreate them? (Only if there is a merge conflict.)
~Where would you suggest I can read with respect to that?~ (done)

**Comment by somedadaism** [comment]
I would disable the mapping in c.vim (instead of overload), will you accept such a request?

**Comment by Netherdrake** [comment]
Sure
